### ISSUE TITLE
Adding Vizio Crashes Companion

### ISSUE THREAD

**Issue by matt-hand** [bitfocus/companion-module-vizio-smartcast#11]
Go through the process of adding a new Vizio TV and apply the changes and Companion crashes. When I relaunch companion the previously added TV has not been added.

**Comment by MichaelAllen** [comment]
@matt-hand Sorry it took me so long to get to this. I was able to reproduce the issue, and have submitted a fix. I will try to remember to post back here when the fix gets pulled in and is available in a build that you can test.

**Comment by matt-hand** [comment]
Thank you so much!

**Comment by MichaelAllen** [comment]
@matt-hand looks like these changes are in the latest beta builds if you want to test it: [https://bitfocus.io/companion/download/builds/](https://bitfocus.io/companion/download/builds/)
