### ISSUE TITLE
Power State not working fully.  Can turn off, but not on

### ISSUE THREAD

**Issue by paulfehr90** [bitfocus/companion-module-vizio-smartcast#19]
Hello!

Not sure if I'm missing something, but the power state command doesn't turn on my TVs when set to "ON", but will turn off when set to "OFF".  If the TV is already on, sending the "ON" power state command will also turn off the tv.

Is this an issue with the firmware on my tv?  I have it set to less than 4.0, as my TVs are on firmware 1.1.7.5

**Comment by ctfrdu** [comment]
I've was having a similar issue. I fixed it by changing the **Power Mode** to **Quick Start** under Menu > System > Power Mode. Also my firmware is 2.7.10-1 but I had to set it >4.0 in the config to get it to pair.

**Comment by josephdadams** [comment]
Your TV can't be in ECO mode, it has to basically stay on all the time (quick start).

You could probably turn it on without Quick Start by sending it a WOL packet first.
