### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by mwb9aa** [bitfocus/companion-module-vizio-smartcast#21]
I installed companion v2.3.1 for Windows from the bitfocus website. I am running Windows 10 with all the latest updates. I added the vizio smartcast connection, and paired my tv. Powering the TV works, as does setting the volume and changing the input.

I can't seem to figure out how to use access the variables. Another [issue](https://github.com/bitfocus/companion-module-vizio-smartcast/issues/20) #20 (closed) mentioned setting up polling in the module, but I don't know how to do that. In the other connections I've used, the variables available for use show up when I click on a button in the Buttons tab of the GUI, and then choose the Variables tab that shows up on the right side. I've attached an image that hopefully is more clear.
![Screenshot 2022-09-20 102436](https://user-images.githubusercontent.com/96304838/191299364-54ee3a3b-ec57-4e00-87f2-e027486cb476.png)

I have checked the companion error log, and there were no errors. I tried to "create" the variable using the same scheme as other modules and the internal scheme. For example, $(internal:date_iso) shows the date, I tried $(A.SmartCast:model_name) to show the model name. When I type in the variable $(A.SmartCast, I get a message from companion that there is no match found.

Thanks for your help.

**Comment by josephdadams** [comment]
My guess is companion v2.3.1 did not have the version of this module that had variables.
