### ISSUE TITLE
Not accepting PIN

### ISSUE THREAD

**Issue by sgberghoff** [bitfocus/companion-module-vizio-smartcast#24]
23.06.13 13:48:48 Instance/Wrapper/smartcast: Error executing action: e.debug is not a function

**Comment by Quildar** [comment]
Not a fix, but a workaround. I downgraded to a previous build I had on hand, specifically "Companion 3.0.0+5446". Ran the pairing sequence and then just ran the new companion, and it linked up.

**Comment by sgberghoff** [comment]
Thank you I'll try that out.

**Comment by matt-hand** [comment]
Thanks for this idea on this. Alas for me I was only able to go back to 5997 as that is the last on the site. I am getting the same error with that build.

**Comment by josephdadams** [comment]
fixed in v2.0.2 of the module
