### ISSUE TITLE
Nothing happening when I hit enter pin

### ISSUE THREAD

**Issue by wcase1** [bitfocus/companion-module-vizio-smartcast#27]
I go through all the steps. I can get the pin to show up on the tv however when I do the "enter pin" button. I click it and nothing happens.

**Comment by JimmyPco** [comment]
same issue using companionpi on V3.0.0. i get this warning in the log.

> Instance/Wrapper/smartcast: Error executing action: e.debug is not a function

**Comment by josephdadams** [comment]
I pushed a fix for this in v2.0.2 of the module
