### ISSUE TITLE
Will Not Pair

### ISSUE THREAD

**Issue by spproduction7224** [bitfocus/companion-module-vizio-smartcast#7]
Pair code works but then nothing happens when I create another command with Pin. Any suggestions?

**Comment by cjluck** [comment]
I can get it to pair (device shows up in Menu -> System -> Mobile Devices on the TV), but other commands don't work.

**Comment by JeffreyDavidsz** [comment]
@MichaelAllen any thoughts?

**Comment by MichaelAllen** [comment]
To clarify, you are saying that the "Pair Device" action causes a code to appear on the TV, but the "Enter Pin" action is not working? Or are both of those working, but none of the other commands?

If you edit the instance after completing the pairing process, is there anything in the field for "Authorization Token"? Unless that field is populated, none of the other actions will work. (The enter pin action should fill it in that field for you)

**Comment by cjluck** [comment]
The code appears on screen when running the Pair Device action, but running the Enter Pin action with that pin does nothing. The authorization token field is not autofilled after running the Enter Pin action.

**Comment by MichaelAllen** [comment]
@spproduction7224 @cjluck If you download the latest companion v2, this module should be fixed now. You may have to delete the instance and re-add it.

**Comment by spproduction7224** [comment]
Ok where is the version 2 download? I only see 1.4 as an option. Thanks

**Comment by spproduction7224** [comment]
Sorry never mind. Got it, thanks. It is now working.
https://bitfocus.io/companion/download/builds/
